name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: v3.6.18
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./re-ML2
      - run: sh ./re-ML2/install.sh
      - run: npm run build
      - name: npm install under ml2scratch
        run: npm install
        working-directory: ./re-ML2
      - name: Build ml2scratch.mjs for xcratch
        run: npm run build
        working-directory: ./re-ML2
      - name: Copy ml2scratch.mjs to build folder
        run: cp ./re-ML2/dist/ml2scratch.mjs ./build
      - name: Copy sample.sb3 to build folder
        run: cp ./re-ML2/sample_projects/xcratch/sample.sb3 ./build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
